In [2]:
import os, datetime
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf
import matplotlib.pyplot as plt
from  sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
data = pd.read_csv("./Downloads/Life Expectancy Data.csv")
data.sample(5)

          Country  Year      Status  ...   thinness 5-9 years  Income composition of resources  Schooling
1681    Mauritius  2001  Developing  ...                  8.0                            0.673       12.2
2618         Togo  2014  Developing  ...                  6.4                            0.475       12.0
1844  Netherlands  2000   Developed  ...                  1.1                            0.873       16.5
1897      Nigeria  2011  Developing  ...                  1.9                            0.500        9.6
742       Denmark  2010   Developed  ...                  0.9                            0.906       16.8

[5 rows x 22 columns]